main: main.o
	g++ -o main main.o
main.o: main.cpp avl_nodes.h avl_functions.h
	g++ -c main.cpp
clean:
	rm *.o
# Makefile

# *****************************************************
# Variables to control Makefile operation
# the compiler: gcc for C program, define as g++ for C++
#CC = g++
# compiler flags:
  #  -g     - this flag adds debugging information to the executable file
  #  -Wall  - this flag is used to turn on most compiler warnings
#CFLAGS = -Wall -g



